version: 2
groups:
  code-quality:
    required: 4
    teams:
      - review-team
    reset_on_push:
      enabled: false

  security:
    conditions:
      files:
        exclude:
          - readme.md
      labels:
        exclude:
          - code-review
    required: -1
    teams:
      - security-team
    reject_value: -100
    reset_on_push:
      enabled: true

  developer:
    conditions:
      files:
        exclude:
          - readme.md
      labels:
        exclude:
          - security-review
          - code-review
    required: 1
    teams:
      - developer
    reset_on_push:
      enabled: false
